### ISSUE TITLE
Actually GradNet-TensorFlow， not  GradNet-Pytorch

### ISSUE THREAD

**Issue by AsuradaYuci** [LPXTT/GradNet-Pytorch#1]
:smiley_cat:

**Comment by zhudd-hub** [comment]
+1

**Comment by ShiLongCheng** [comment]
where is the repository of Pytorch version? or when the Pytorch version can be pushed into github?THX.

**Comment by LPXTT** [comment]
I am so sorry for the mistake. Actually, there is no Pytorch version. The
origin code is based on tensorflow.
I will change the misleading message as soon as possible.
Thank you very much for the notification~
