### ISSUE TITLE
train problem

### ISSUE THREAD

**Issue by INTOUCHABLE-VS** [LPXTT/GradNet-Pytorch#10]
您好，我前段时间在学习复现这篇论文，但是发现训练代码里使用的是您论文里说所说的Ours-T训练形式，而不是您所提出的template generation训练形式，请问是否是您上传代码有误呢？期待您的答复

**Comment by LPXTT** [comment]
您好，上传代码是没有问题的。 你可以参考siamese.py 的第86行代码，这里计算loss的时候是只用了 template0。

**Comment by INTOUCHABLE-VS** [comment]
> 您好，上传代码是没有问题的。 你可以参考siamese.py 的第86行代码，这里计算loss的时候是只用了 template0。

我看到了确实是这样。另外我想请教您，您在论文里是使用的4，代码里是8，看注释您应该也运行过4，结果影响大吗？我觉得使用的越多带来的误差也会越大，不过梯度的比例可能也会更高，不知道您的看法如何？

**Comment by INTOUCHABLE-VS** [comment]
> 您好，上传代码是没有问题的。 你可以参考siamese.py 的第86行代码，这里计算loss的时候是只用了 template0。

我看到了确实是这样。另外我想请教您，您在论文里是使用的4，代码里是8，看注释您应该也运行过4，结果影响大吗？我觉得使用的越多带来的误差也会越大，不过梯度的比例可能也会更高，不知道您的看法如何？

**Comment by LPXTT** [comment]
不好意思，您这里说的4和8是什么？

**Comment by INTOUCHABLE-VS** [comment]
> 不好意思，您这里说的4和8是什么？

batchsize，也就是如您Siamese.py的第86行代码，当batchsize = 8，这时候template generation相当于使用了八个。我看到您的训练代码注释了batchsize = 4，所以想问一下是否有影响？我觉得使用的越多带来的误差也会越大，不过梯度的比例可能也会更高，不知道您的看法如何？

**Comment by LPXTT** [comment]
batch size确实会对结果产生一定的影响，这里4确实比8要差一些。

**Comment by INTOUCHABLE-VS** [comment]
> batch size确实会对结果产生一定的影响，这里4确实比8要差一些。

好的，非常感谢您的答复
